highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
repository: naighes/naighes.github.io
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
title: Nicola Baldi @naighes
description: Nicola's personal page and resume.
url: https://naighes.github.io/
author: Nicola Baldi
twitter:
  username: nicolabaldi
logo: images/contents/NB.jpeg
social:
  name: Naighes
  links:
    - https://twitter.com/nicolabaldi
    - https://www.linkedin.com/in/nicolabaldi/
    - https://github.com/naighes
    - https://www.slideshare.net/Naighes
